Replace execSync Node module with sync-exec
Using Node 0.12.0 with execSync 1.0.2 produces the following error:
Native code compile failed!!

Since execSync fails to properly install, none of the Gulp tasks are
able to run:
Cannot find module './build/Release/shell'